### ISSUE TITLE
Print PDF broken (404) in the view cloud usage page

### ISSUE THREAD

**Issue by crazyCat76** [ibm-cloud-docs/billing-usage#1]
Hello,

This page : https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-viewingusage
Cannot be printed to pdf, it gives a 404.

Otherwise, it's a good job ;)

Regards,

**Comment by cjcarpen** [comment]
Hi @crazyCat76 , thanks for opening this issue! We're continuing to refine this functionality and have removed it in the meantime.
