### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by MichaelTriguboff** [ibm-cloud-docs/billing-usage#3]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by MichaelTriguboff** [comment]
How do I find my usage and billing options- I am a student taking an IBM Practical Certificate course-thanks

**Comment by hlucey** [comment]
Hi @MichaelTriguboff, 

You can find all your usage and billing information by going to https://cloud.ibm.com/billing. If you are unable to view specific billing information, you can reach out to [IBM Cloud Support](https://cloud.ibm.com/unifiedsupport/supportcenter).

**Comment by MichaelTriguboff** [comment]
Hi The problem has not been resolved. My account is in credit and yet I am denied access because the message says I have used my monthly limit. I am on a Pay as You Go basis and IBM has my credit card information. I need help

**Comment by hlucey** [comment]
@MichaelTriguboff I'm sorry you're having an issue related to billing and monthly usage. Please go to [IBM Cloud Support](https://cloud.ibm.com/unifiedsupport/supportcenter)to open a support case. Our support team can look into this issue.
