### ISSUE TITLE
Metered vs Tiered Terminology 

### ISSUE THREAD

**Issue by douglin** [ibm-cloud-docs/billing-usage#3]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?  My customers and other parts of IBM/GBS are confused by the metered and tiered terminology.  

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-charges

3. Do you have a suggestion about how to resolve the issue?
GBS suggested changing metered to "unit based" and tiered to "variable - tiered"

**Comment by hlucey** [comment]
Updating examples and definitions for both meter and tiered terminology.

**Comment by KentHall2018** [comment]
@hlucey was this updated and can this be closed?

**Comment by hlucey** [comment]
In progress @KentHall2018, waiting on edits from Courtney! (should be closed soon)

**Comment by KentHall2018** [comment]
@cdmauney were you able to look over the changes for this doc?
- [How you're charged](https://test.cloud.ibm.com/docs/billing-usage?topic=billing-usage-charges)

**Comment by hlucey** [comment]
Updated the documentation for the metered and tiered terminology.
