### ISSUE TITLE
featur code erro

### ISSUE THREAD

**Issue by Dineshwaran143** [ibm-cloud-docs/billing-usage#7]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by hlucey** [comment]
Hi @Dineshwaran143, 

I see you that you might have a question regarding feature codes. You can find the documentation for feature codes here: https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-codes and https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cannot-apply-feature-code. If this problem persists, please open another issue with details about the problem. Thanks!
