### ISSUE TITLE
Provide more info about fixed monthly rate items

### ISSUE THREAD

**Issue by vfandino** [ibm-cloud-docs/billing-usage#7]
For monthly rate items (for instance bare metal servers), charge is done in the moment you create them (in the credit card, for instance), not at the end of the billing period. I think this information should appear in the documentation.  Also, the doc should explain that the charge is done prorating the cost to the end of the period.

Thank you very much

https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-charges

**Comment by hlucey** [comment]
Issue opened to address doc updates. Working with billing squad to provide more information.
