### ISSUE TITLE
Error  Could not place order. Problem authorizing the credit card. We are unable to process your request: Transaction Rejected. Please contact Cloud Trust Enablement at verify@us.ibm.com for further information. Code: 54cdc5e6-32bd-45ae-84dd-44810bf5a4ba

### ISSUE THREAD

**Issue by tunghs81** [ibm-cloud-docs/billing-usage#9]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by tunghs81** [comment]
i tried to create an account in IBM Db2 Cloud for lite package. When i am creating the account, there is message saying that my account at Sydney where i cannot create create under Lite package but need to create the as you go package start with 200 dollar credit. So, when the moment i click on the upgrade, it end the processing by providing this message 

"Error Could not place order. Problem authorizing the credit card. We are unable to process your request: Transaction Rejected. Please contact Cloud Trust Enablement at verify@us.ibm.com for further information.
Code: 54cdc5e6-32bd-45ae-84dd-44810bf5a4ba" .

 i was then caught in the loop and had keep on trying for 8 attempt, and all ended with the upgrade, and it ended with the same message "Error Could not place order. Problem authorizing the credit card. We are unable to process your request: Transaction Rejected. Please contact Cloud Trust Enablement at verify@us.ibm.com for further information.
Code: 54cdc5e6-32bd-45ae-84dd-44810bf5a4ba"

Please advise

**Comment by KentHall2018** [comment]
@tunghs81 thanks for opening this issue. did you contact [verify@us.ibm.com](mailto:verify@us.ibm.com)? along with contacting the email, you can also take a look at our documentation and go through the steps for verifying your transaction details as well as a number to contact by phone: https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cc-error-messages#trans-rejected
